### ISSUE TITLE
有没有考虑放个语雀

### ISSUE THREAD

**Issue by ScienGU** [wdndev/llm_interview_note#1]

**Comment by wdndev** [comment]
准备考虑往github page上迁移

**Comment by wdndev** [comment]
在线阅读链接已更新，暂不考虑迁移至语雀

https://dongnian.icu/llm_interview_note

**Comment by lyh1028** [comment]
> 在线阅读链接已更新，暂不考虑迁移至语雀
> 
> https://dongnian.icu/llm_interview_note

小红书上有人拿你的笔记做推广，是本人吗

**Comment by wdndev** [comment]
我没有任何小红书账号，知乎也是推荐过一次，就一个微信公众号，半死不活的
